# Generated by Django 2.2.17 on 2020-11-16 02:24

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration', models.IntegerField(max_length=11)),
                ('password', models.CharField(max_length=200)),
                ('registration_type', models.IntegerField(choices=[(0, 'Estudante'), (1, 'Monitor')])),
                ('photo', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem')),
                ('about', models.TextField(max_length=400)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
