# Generated by Django 2.2.17 on 2020-11-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender_choice', models.IntegerField(choices=[(0, 'Masculino'), (1, 'Feminino')])),
            ],
        ),
    ]
