# Generated by Django 2.2.17 on 2020-11-20 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201120_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_type',
        ),
    ]
