# Generated by Django 2.2.17 on 2020-11-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
