# Generated by Django 2.2.17 on 2020-12-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201210_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
    ]
