# Generated by Django 2.2.17 on 2020-11-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201116_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
