# Generated by Django 2.2.17 on 2020-12-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
