# Generated by Django 2.2.17 on 2020-12-13 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201213_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requisitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitioner', to=settings.AUTH_USER_MODEL),
        ),
    ]
